sudo: required
dist: trusty
language: node

before_script:
  # install v6.x of nodejs
   - nvm install 10.11
  #install yarn globally
   - npm install -g yarn
  # yarn install is like npm install
   - yarn install

script:
  - yarn install
  - yarn psc-package
  - yarn build
  - yarn test
